sudo: required
language: csharp
mono: none
matrix:
  include:
    - os: linux    
      dotnet: 2.1
    - os: osx
      dotnet: 2.1.300
services:
 - mongodb
 - redis-server
script:
 - dotnet publish
 - dotnet test NetCoreReactReduxAdvanced.IntegrationTest