sudo: required
language: csharp
mono: none
dotnet: 2.1
os:
 - windows
 - linux
 - osx
services:
 - mongodb
 - redis-server
script:
 - dotnet publish
 - dotnet test NetCoreReactReduxAdvanced.IntegrationTest