sudo: required
language: csharp
mono: none
matrix:
  include:
    - os: linux    
      dotnet: 2.1
      services:
        - mongodb
        - redis-server
    - os: osx
      dotnet: 2.1.300
      before_install:
        - brew install mongodb
        - brew services start mongodb
        - brew install redis
        - brew services start redis
script:
 - dotnet publish
 - dotnet test NetCoreReactReduxAdvanced.IntegrationTest