version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
install:
  # Install repo specific stuff here
services:
  - mongodb  
before_build:
  # Display .NET Core version
  - choco install redis-64
  - redis-server --service-install
  - redis-server --service-start  
  - cmd: dotnet --version
build_script:
  - cmd: dotnet publish
after_build:
  # For once the build has completed
artifacts:
clone_depth: 1
test_script:
  - cmd: dotnet test NetCoreReactReduxAdvanced.IntegrationTest
on_finish :
  # any cleanup in here
deploy: off